import { Fragment, useRef, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import { Input } from '@nextui-org/react'
import { SendButton } from './common/SendButton'
import { SendIcon } from './common/SendIcon'
const { Configuration, OpenAIApi } = require('openai')
const configuration = new Configuration({
  apiKey: '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',
})
const openai = new OpenAIApi(configuration)
export default function Home() {
  // 搜索数据
  const ref = useRef()
  // 是否开启openai
  const [isOpenai, setIsOpenai] = useState(false)
  /**
   * @description 搜索
   */
  const searchGPT = async () => {
    const completion = await openai.createCompletion({
      model: 'text-davinci-003',
      prompt: ref.current.value,
    })
    console.log(completion.data.choices[0].text)
  }
  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isOpenai ? (
          <Fragment>
            <div>
              <Input
                ref={ref}
                clearable
                contentRightStyling={false}
                placeholder="Ask a question..."
                aria-label="Search"
                contentRight={
                  <SendButton onClick={searchGPT}>
                    <div className={styles.send}>
                      <span style={{ marginLeft: '10px' }}>Send</span>
                      <SendIcon />
                    </div>
                  </SendButton>
                }
              />
            </div>
          </Fragment>
        ) : (
          <Fragment>
            <div
              className={styles.description}
              onClick={() => setIsOpenai(true)}
            >
              <p>
                <span style={{ fontSize: '20px' }}>
                  Welcome to my blog&nbsp;
                </span>
                <code className={styles.code}>
                  please accept my thanks, now and always.
                </code>
              </p>
              <div>
                <a style={{ cursor: 'pointer' }}>
                  By
                  <Image
                    src="photo.svg"
                    alt="Vercel Logo"
                    className={styles.vercelLogo}
                    width={40}
                    height={40}
                    priority
                  />
                  <span style={{ fontSize: '24px' }}>Openai</span>
                </a>
              </div>
            </div>
          </Fragment>
        )}
        {/* 主体 */}
        <div className={styles.center}>
          <div>
            <span className={styles.pdd}>pdd</span>
            <span style={{ marginLeft: '20px', fontSize: '20px' }}>.blog</span>
          </div>
          {/* 简单 */}
          <div className={styles.simple}>简单</div>
          <div className={styles.only}>唯一</div>
          {/* 唯一 */}
        </div>
        {/* 导航 */}
        <div className={styles.grid}>
          <a
            href="https://tzwtmll.github.io/docs"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {/* Find in-depth information about Next.js features and&nbsp;API. */}
              查找有关前端技术与文章和原理的技术博客。
            </p>
          </a>

          <a
            href="https://tzwtmll.github.io/image"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Image <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {/* Learn about Next.js in an interactive course with&nbsp;quizzes! */}
              {/* 在带有测验的交互式课程中了解 Next.js！ */}
              了解我的摄影作品，或提出建议，或指出不足
            </p>
          </a>
          <a
            href="https://tzwtmll.github.io/phototheme"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Theme <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              摄影主题在后续中会逐渐完善 现在正在开发中
            </p>
          </a>
          {/* 第四格 */}
          <a
            href="https://tzwtmll.github.io/rust"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Rust <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              面向安全编程 更快的编译速度 更安全的内存管理 相对于C++更加简单
              广泛运用于前端工具的编写 逐渐完善的生态
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
