import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <span style={{ fontSize: '20px' }}>Welcome to my blog&nbsp;</span>
            <code className={styles.code}>
              please accept my thanks, now and always.
            </code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By
              <Image
                src="vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        {/* 主体 */}
        <div className={styles.center}>
          <div>
            <span className={styles.pdd}>pdd</span>
            <span style={{ marginLeft: '20px', fontSize: '20px' }}>.blog</span>
          </div>
        </div>
        {/* 导航 */}
        <div className={styles.grid}>
          <a
            href="https://tzwtmll.github.io/docs"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {/* Find in-depth information about Next.js features and&nbsp;API. */}
              查找有关 前端 技术与文章和 原理 的技术博客。
            </p>
          </a>

          <a
            href="https://tzwtmll.github.io/image"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Image <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {/* Learn about Next.js in an interactive course with&nbsp;quizzes! */}
              {/* 在带有测验的交互式课程中了解 Next.js！ */}
              了解我的摄影作品 或提出建议 或指出不足
            </p>
          </a>
          <a
            href="https://tzwtmll.github.io/phototheme"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Theme <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              摄影主题在后续中会逐渐完善 现在正在开发中
            </p>
          </a>
          <a
            href="https://tzwtmll.github.io/v2docs"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              文档2.0 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              更加简洁的二代文档&nbsp;正在开发中.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
